name: bd-sig-action 

on:
  push:
    branches: [ sarif-upload ]
jobs:
  build:
    runs-on: [ mac ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
          
      - name: Black Duck Full Scan
        if: ${{ github.event_name != 'pull_request' }}
        uses: synopsys-sig/synopsys-action@upload-sarif
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
          DETECT_PROJECT_VERSION_NAME: ${{ github.ref_name }}
          DETECT_CODE_LOCATION_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}
        with:
          BlaCkDucK_UrL: ${{ secrets.BLACKDUCK_URL }}
          BlaCkdUck_aPITokEn: ${{ secrets.BLACKDUCK_API_TOKEN }}
          upload_sarif_file: '/Users/spurohit/.bridge/polaris_results.sarif.json'
          github_token: ${{ secrets.GITHUB_TOKEN }}
