name: bd-sig-action

on:
  push:
    branches: [ main, master, develop, stage, release, sarif-test ]
jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Black Duck Full Scan
        if: ${{ github.event_name != 'pull_request' }}
        uses: synopsys-sig/synopsys-action@v1.11.0
        ### Use below configuration to set specific detect environment variables
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
        with:
          synopsys_bridge_download_version: "2.6.0"
          blackduck_url: ${{ secrets.BLACKDUCK_URL }}
          blackduck_apiToken: ${{ secrets.BLACKDUCK_API_TOKEN }}
          blackduck_reports_sarif_create: true # Create Black Duck SARIF report and upload it as artifact
          blackduck_upload_sarif_report: true  # Upload Black Duck SARIF report in GitHub Advanced Security tab
          github_token: ${{ secrets.GITHUB_TOKEN }} # Required when blackduck_upload_sarif_report is set as true
